// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeJfnLXhClOtImJ8E1gJ8p6rcbbIS6p8U',
    appId: '1:475092803921:web:1b28a98a1b5f268626f370',
    messagingSenderId: '475092803921',
    projectId: 'newswordapp-7a53b',
    authDomain: 'newswordapp-7a53b.firebaseapp.com',
    storageBucket: 'newswordapp-7a53b.firebasestorage.app',
    measurementId: 'G-YYFT709LDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzIOuXIl2E-huH5N8N83TMx5srLzsOK2Y',
    appId: '1:475092803921:android:b5f26200923559c626f370',
    messagingSenderId: '475092803921',
    projectId: 'newswordapp-7a53b',
    storageBucket: 'newswordapp-7a53b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA27iaLCj3JXwXH35wZyDdijEpUbGBRdU0',
    appId: '1:475092803921:ios:81503c7456d55eb226f370',
    messagingSenderId: '475092803921',
    projectId: 'newswordapp-7a53b',
    storageBucket: 'newswordapp-7a53b.firebasestorage.app',
    iosBundleId: 'com.example.wordapp',
  );
}
